starting binaryen codegen
The-Bird-Programming-Langauge/bird-lang pull request #95
Opened 2024-11-08 04:03 UTC by nathanwrightUNR

2024-11-11 19:40 UTC, colecarley requested changes

2024-11-11 19:40 UTC, colecarley commented on include/visitors/code_gen.h
> +    std::shared_ptr<Environment<BinaryenExpressionRef>> environment;
I don't think this needs to be a shared_ptr

2024-11-11 19:40 UTC, colecarley commented on include/visitors/code_gen.h
> +        this->std_lib["print"] = "printf";
I don't think we need this map anymore.

2024-11-11 19:40 UTC, colecarley commented on include/visitors/code_gen.h
> +        // format string and pointer as param for printf
The environment will inject JavaScript's `console.log` function instead of c's `printf` function, so the parameters and results will be different.

2024-11-11 19:40 UTC, colecarley commented on include/visitors/code_gen.h
> +            return BinaryenTypeInt32(); // no i1?
The only types are `i32`, `i64`, `f32`, and `f64`. You've got it right in the code here. Bools are represented by `i32`.

2024-11-11 19:40 UTC, colecarley commented on include/visitors/code_gen.h
> +        int index = this->local_index++;
This should probably be reset after each function. Maybe Binaryen has an auto incrementor?

2024-11-11 19:40 UTC, colecarley commented on include/visitors/code_gen.h
> +        BinaryenExpressionRef set_local = BinaryenLocalSet(this->mod, index, initializer_value);
I think a local set is the right thing here, but I do want to point out that the data will only persist during a function's lifetime. Eventually, when we want something to persist over the span of multiple functions, we will use the load and store functions.

2024-11-11 19:40 UTC, colecarley commented on include/visitors/code_gen.h
> +        for (auto &arg : print_stmt->args)
Let's wait on the print statement for now cause there are still a lot of unknowns here.

2024-11-11 19:40 UTC, colecarley commented on include/visitors/code_gen.h
> +        auto printfFunc = this->std_lib["print"];
We can remove the map and just refer to the function by name.

2024-11-11 19:40 UTC, colecarley commented on include/visitors/code_gen.h
> +        case Token::Type::PLUS:
I believe there is a concat operator for strings

2024-11-11 19:40 UTC, colecarley commented on include/visitors/code_gen.h
> +            BinaryenExpressionRef var = this->environment->get(primary->value.lexeme);
I think you'll have to do a local set here?

2024-11-11 19:40 UTC, colecarley commented on include/visitors/code_gen.h
> +        // throw BirdException("Implement Ternart Statement");
Theres a nice instruction called `select` you should check out

2024-11-22 04:58 UTC, colecarley approved these changes

2024-11-22 05:10 UTC, Nicholas-Langley approved these changes

2024-11-22 05:11 UTC, merged